trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'


  - script: |
      npm run build
    displayName: 'Build development environment'

  - task: CopyFiles@2
    inputs:
      contents: 'build/**'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy /build to artifacts staging directory'

  - task: CopyFiles@2
    inputs:
      contents: '*firebase.json'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy firebase.json to artifacts staging directory'


  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: app
    displayName: 'Publish artifacts'
